-- Generated by scripts/dump-test-schema.sh from the schema of 'personal-billing'.
-- Structure for every table, plus rows for: bill_statuses payment_types categories sync_settings sql_migrations
-- Regenerate after any migration. Do not hand-edit.


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `__drizzle_migrations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `__drizzle_migrations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hash` text NOT NULL,
  `created_at` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `account_balances`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `account_balances` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `balance` decimal(12,2) NOT NULL,
  `as_of` date NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `credit_limit` decimal(12,2) DEFAULT NULL,
  `apr` decimal(5,2) DEFAULT NULL,
  `min_payment` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ab_acct` (`account_id`),
  KEY `idx_ab_date` (`as_of`),
  CONSTRAINT `account_balances_account_id_accounts_id_fk` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=281 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `accounts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_number` varchar(8) NOT NULL,
  `label` varchar(64) DEFAULT NULL,
  `institution` varchar(64) DEFAULT NULL,
  `account_type` varchar(32) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `original_principal` decimal(12,2) DEFAULT NULL,
  `opened_on` date DEFAULT NULL,
  `notes` text,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `bill_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_acct` (`account_number`),
  UNIQUE KEY `uq_acct_bill` (`bill_id`),
  CONSTRAINT `accounts_bill_id_bills_id_fk` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=512 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `bill_instances`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bill_instances` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `period_id` int(11) NOT NULL,
  `bill_id` int(11) DEFAULT NULL,
  `name` varchar(191) NOT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `due_day` tinyint(4) DEFAULT NULL,
  `payment_type` varchar(32) DEFAULT NULL,
  `is_debt` tinyint(1) NOT NULL DEFAULT '0',
  `is_cancel` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_bi_period` (`period_id`),
  KEY `idx_bi_bill` (`bill_id`),
  CONSTRAINT `bill_instances_bill_id_bills_id_fk` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `bill_instances_period_id_periods_id_fk` FOREIGN KEY (`period_id`) REFERENCES `periods` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=299 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `bill_statuses`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bill_statuses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL,
  `color` varchar(16) NOT NULL DEFAULT '#9ca3af',
  `is_settled` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `emoji` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_status_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=97 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `bills`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(191) NOT NULL,
  `default_amount` decimal(10,2) DEFAULT NULL,
  `default_due_day` tinyint(4) DEFAULT NULL,
  `default_payment_type` varchar(32) DEFAULT NULL,
  `is_debt` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_bill_name` (`name`),
  KEY `idx_bill_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `budget_lines`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `budget_lines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `budget_id` int(11) NOT NULL,
  `kind` varchar(16) NOT NULL,
  `label` varchar(191) NOT NULL,
  `category` varchar(48) DEFAULT NULL,
  `account_id` int(11) DEFAULT NULL,
  `planned` decimal(12,2) NOT NULL DEFAULT '0.00',
  `minimum` decimal(12,2) DEFAULT NULL,
  `is_target` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `notes` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `locked` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_bl_budget` (`budget_id`),
  KEY `idx_bl_account` (`account_id`),
  CONSTRAINT `fk_bl_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_bl_budget` FOREIGN KEY (`budget_id`) REFERENCES `budgets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `budgets`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `budgets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `period_id` int(11) NOT NULL,
  `mode` varchar(32) NOT NULL DEFAULT 'manual',
  `strategy` varchar(32) DEFAULT NULL,
  `planned_income` decimal(12,2) DEFAULT NULL,
  `notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `auto_rebalance` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_budget_period` (`period_id`),
  CONSTRAINT `fk_budget_period` FOREIGN KEY (`period_id`) REFERENCES `periods` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `cash_allocations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cash_allocations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `withdrawal_txn_id` int(11) NOT NULL,
  `spend_txn_id` int(11) NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cash_alloc` (`withdrawal_txn_id`,`spend_txn_id`),
  KEY `idx_ca_withdrawal` (`withdrawal_txn_id`),
  KEY `idx_ca_spend` (`spend_txn_id`),
  CONSTRAINT `fk_ca_spend` FOREIGN KEY (`spend_txn_id`) REFERENCES `transactions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ca_withdrawal` FOREIGN KEY (`withdrawal_txn_id`) REFERENCES `transactions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(48) NOT NULL,
  `color` varchar(16) NOT NULL DEFAULT '#9ca3af',
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `emoji` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_category_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `category_mappings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `category_mappings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `match_type` varchar(12) NOT NULL,
  `pattern` varchar(255) NOT NULL,
  `field` varchar(16) NOT NULL DEFAULT 'description',
  `category` varchar(48) NOT NULL,
  `bill_id` int(11) DEFAULT NULL,
  `priority` int(11) NOT NULL DEFAULT '100',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `category_mappings_bill_id_bills_id_fk` (`bill_id`),
  CONSTRAINT `category_mappings_bill_id_bills_id_fk` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=117 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `debt_balances`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `debt_balances` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `debt_id` int(11) NOT NULL,
  `balance` decimal(12,2) NOT NULL,
  `apr` decimal(5,2) DEFAULT NULL,
  `min_payment` decimal(10,2) DEFAULT NULL,
  `as_of` date NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_db_debt` (`debt_id`),
  KEY `idx_db_date` (`as_of`),
  CONSTRAINT `debt_balances_debt_id_debts_id_fk` FOREIGN KEY (`debt_id`) REFERENCES `debts` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `debts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `debts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bill_id` int(11) NOT NULL,
  `original_principal` decimal(12,2) DEFAULT NULL,
  `opened_on` date DEFAULT NULL,
  `notes` text,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_debt_bill` (`bill_id`),
  CONSTRAINT `debts_bill_id_bills_id_fk` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `goal_contributions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `goal_contributions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `goal_id` int(11) NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `occurred_on` date NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `transaction_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `goal_contributions_transaction_id_transactions_id_fk` (`transaction_id`),
  KEY `idx_gc_goal` (`goal_id`),
  KEY `idx_gc_date` (`occurred_on`),
  CONSTRAINT `goal_contributions_goal_id_savings_goals_id_fk` FOREIGN KEY (`goal_id`) REFERENCES `savings_goals` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `goal_contributions_transaction_id_transactions_id_fk` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `import_batches`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `import_batches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `source` varchar(64) DEFAULT NULL,
  `account_id` int(11) DEFAULT NULL,
  `total_rows` int(11) NOT NULL,
  `inserted_count` int(11) NOT NULL,
  `duplicate_count` int(11) NOT NULL,
  `error_count` int(11) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `import_batches_account_id_accounts_id_fk` (`account_id`),
  CONSTRAINT `import_batches_account_id_accounts_id_fk` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `pay_schedule`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `pay_schedule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `frequency` varchar(32) NOT NULL DEFAULT 'semimonthly',
  `day_one` int(11) DEFAULT NULL,
  `day_two` int(11) DEFAULT NULL,
  `anchor_date` date DEFAULT NULL,
  `take_home` decimal(12,2) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deposit_window_days` int(11) NOT NULL DEFAULT '3',
  `deposit_match` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `payment_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `payment_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL,
  `color` varchar(16) NOT NULL DEFAULT '#9ca3af',
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `emoji` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ptype_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `periods`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `periods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `year` smallint(6) NOT NULL,
  `month` tinyint(4) NOT NULL,
  `label` varchar(20) NOT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_period` (`year`,`month`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `projection_snapshots`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `projection_snapshots` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `period_id` int(11) NOT NULL,
  `taken_on` date NOT NULL,
  `as_of` date NOT NULL,
  `cash_now` decimal(12,2) NOT NULL,
  `end_balance` decimal(12,2) NOT NULL,
  `horizon_balance` decimal(12,2) NOT NULL,
  `low_balance` decimal(12,2) NOT NULL,
  `low_date` date NOT NULL,
  `spread_total` decimal(12,2) NOT NULL,
  `hot_end` decimal(12,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_proj_snap` (`period_id`,`taken_on`),
  CONSTRAINT `fk_ps_period` FOREIGN KEY (`period_id`) REFERENCES `periods` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=999 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `savings_goals`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `savings_goals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(191) NOT NULL,
  `goal_type` varchar(32) NOT NULL DEFAULT 'savings',
  `target_amount` decimal(12,2) NOT NULL,
  `target_date` date DEFAULT NULL,
  `funding_account_id` int(11) DEFAULT NULL,
  `color` varchar(16) NOT NULL DEFAULT '#3b82f6',
  `emoji` varchar(16) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_goal_status` (`status`),
  KEY `idx_goal_acct` (`funding_account_id`),
  CONSTRAINT `savings_goals_funding_account_id_accounts_id_fk` FOREIGN KEY (`funding_account_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sql_migrations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sql_migrations` (
  `filename` varchar(255) NOT NULL,
  `applied_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `note` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `suggestion_dismissals`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `suggestion_dismissals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `merchant_key` varchar(191) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_suggestion_key` (`merchant_key`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sync_accounts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sync_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enrollment_id` int(11) NOT NULL,
  `external_account_id` varchar(64) NOT NULL,
  `name` varchar(128) DEFAULT NULL,
  `type` varchar(16) DEFAULT NULL,
  `subtype` varchar(32) DEFAULT NULL,
  `last_four` varchar(4) DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `account_id` int(11) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `sync_balances` tinyint(1) NOT NULL DEFAULT '1',
  `sync_from` date DEFAULT NULL,
  `external_status` varchar(16) NOT NULL DEFAULT 'open',
  `last_synced_at` timestamp NULL DEFAULT NULL,
  `last_error` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sync_account` (`external_account_id`),
  UNIQUE KEY `uq_sync_account_local` (`account_id`),
  KEY `idx_sa_enrollment` (`enrollment_id`),
  KEY `idx_sa_account` (`account_id`),
  CONSTRAINT `sync_accounts_account_id_accounts_id_fk` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `sync_accounts_enrollment_id_sync_enrollments_id_fk` FOREIGN KEY (`enrollment_id`) REFERENCES `sync_enrollments` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sync_enrollments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sync_enrollments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `provider` varchar(16) NOT NULL,
  `enrollment_id` varchar(64) NOT NULL,
  `institution_id` varchar(64) DEFAULT NULL,
  `institution_name` varchar(128) DEFAULT NULL,
  `provider_user_id` varchar(64) DEFAULT NULL,
  `access_token_enc` text NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `disconnect_reason` varchar(64) DEFAULT NULL,
  `enrolled_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_synced_at` timestamp NULL DEFAULT NULL,
  `last_error` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sync_enrollment` (`provider`,`enrollment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=117 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sync_ignored`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sync_ignored` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source` varchar(16) NOT NULL,
  `external_id` varchar(64) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sync_ignored` (`source`,`external_id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sync_runs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sync_runs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `trigger` varchar(16) NOT NULL,
  `enrollment_id` int(11) DEFAULT NULL,
  `status` varchar(12) NOT NULL DEFAULT 'running',
  `dry_run` tinyint(1) NOT NULL DEFAULT '0',
  `started_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` timestamp NULL DEFAULT NULL,
  `inserted` int(11) NOT NULL DEFAULT '0',
  `updated` int(11) NOT NULL DEFAULT '0',
  `promoted` int(11) NOT NULL DEFAULT '0',
  `expired` int(11) NOT NULL DEFAULT '0',
  `skipped_dupes` int(11) NOT NULL DEFAULT '0',
  `balances_recorded` int(11) NOT NULL DEFAULT '0',
  `error` text,
  `details` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sync_runs_enrollment_id_sync_enrollments_id_fk` (`enrollment_id`),
  KEY `idx_sr_started` (`started_at`),
  CONSTRAINT `sync_runs_enrollment_id_sync_enrollments_id_fk` FOREIGN KEY (`enrollment_id`) REFERENCES `sync_enrollments` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=532 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `sync_settings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sync_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `interval_minutes` int(11) NOT NULL DEFAULT '180',
  `sync_window_days` int(11) NOT NULL DEFAULT '10',
  `pending_expiry_days` int(11) NOT NULL DEFAULT '7',
  `record_balances` tinyint(1) NOT NULL DEFAULT '1',
  `auto_categorize` tinyint(1) NOT NULL DEFAULT '1',
  `webhook_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `lock_until` timestamp NULL DEFAULT NULL,
  `next_run_at` timestamp NULL DEFAULT NULL,
  `last_run_id` int(11) DEFAULT NULL,
  `last_webhook_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `transaction_splits`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `transaction_splits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `txn_id` int(11) NOT NULL,
  `category` varchar(48) NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ts_txn` (`txn_id`),
  KEY `idx_ts_cat` (`category`),
  CONSTRAINT `fk_ts_txn` FOREIGN KEY (`txn_id`) REFERENCES `transactions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `transactions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) DEFAULT NULL,
  `period_id` int(11) DEFAULT NULL,
  `bill_instance_id` int(11) DEFAULT NULL,
  `txn_date` date NOT NULL,
  `description` varchar(512) NOT NULL,
  `category` varchar(48) DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `net_amount` decimal(12,2) DEFAULT NULL,
  `direction` varchar(8) NOT NULL,
  `dedup_hash` char(64) NOT NULL,
  `import_batch_id` int(11) DEFAULT NULL,
  `raw` json DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `transfer_partner_id` int(11) DEFAULT NULL,
  `bill_id` int(11) DEFAULT NULL,
  `notes` text,
  `category_rule_id` int(11) DEFAULT NULL,
  `source` varchar(16) NOT NULL DEFAULT 'import',
  `external_id` varchar(64) DEFAULT NULL,
  `status` varchar(12) NOT NULL DEFAULT 'posted',
  `pending` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_dedup` (`dedup_hash`),
  UNIQUE KEY `uq_tx_external` (`source`,`external_id`),
  KEY `transactions_period_id_periods_id_fk` (`period_id`),
  KEY `transactions_import_batch_id_import_batches_id_fk` (`import_batch_id`),
  KEY `idx_tx_date` (`txn_date`),
  KEY `idx_tx_acct` (`account_id`),
  KEY `idx_tx_cat` (`category`),
  KEY `transactions_transfer_partner_id_transactions_id_fk` (`transfer_partner_id`),
  KEY `idx_tx_bill` (`bill_id`),
  KEY `transactions_bill_instance_id_bill_instances_id_fk` (`bill_instance_id`),
  KEY `idx_tx_cat_rule` (`category_rule_id`),
  KEY `idx_tx_status` (`status`),
  KEY `idx_tx_pending` (`pending`),
  CONSTRAINT `transactions_account_id_accounts_id_fk` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `transactions_bill_id_bills_id_fk` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `transactions_bill_instance_id_bill_instances_id_fk` FOREIGN KEY (`bill_instance_id`) REFERENCES `bill_instances` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `transactions_category_rule_id_category_mappings_id_fk` FOREIGN KEY (`category_rule_id`) REFERENCES `category_mappings` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `transactions_import_batch_id_import_batches_id_fk` FOREIGN KEY (`import_batch_id`) REFERENCES `import_batches` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `transactions_period_id_periods_id_fk` FOREIGN KEY (`period_id`) REFERENCES `periods` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `transactions_transfer_partner_id_transactions_id_fk` FOREIGN KEY (`transfer_partner_id`) REFERENCES `transactions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2973 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `transfer_dismissals`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `transfer_dismissals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `low_id` int(11) NOT NULL,
  `high_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_dismissal` (`low_id`,`high_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;



/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `bill_statuses` DISABLE KEYS */;
INSERT INTO `bill_statuses` (`id`, `name`, `color`, `is_settled`, `sort_order`, `active`, `created_at`, `updated_at`, `emoji`) VALUES (1,'Unpaid','#cfcfcf',0,0,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(2,'Optional','#9ca3af',1,1,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(3,'Not Due Yet','#64748b',0,2,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(4,'Past Due','#b91c1c',0,3,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','⏰'),(5,'Debt','#f97316',0,4,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(6,'Autopay','#3b82f6',1,5,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(7,'Ready for Payment','#f59e0b',0,6,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(8,'Pending','#eab308',0,7,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','⏳'),(9,'Partial Payment','#a855f7',0,8,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(10,'Autopay Pending','#0ea5e9',0,9,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(11,'Declined','#f43f5e',0,10,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','❌'),(12,'Paid/Purchased','#22c55e',1,11,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','✅'),(13,'Paid & Cancelled','#10b981',1,12,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(14,'Suspended','#71717a',1,13,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','⏸️'),(15,'No Balance','#14b8a6',1,14,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(16,'Skipped','#d4d4d8',1,15,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','⏭️');
/*!40000 ALTER TABLE `bill_statuses` ENABLE KEYS */;

/*!40000 ALTER TABLE `payment_types` DISABLE KEYS */;
INSERT INTO `payment_types` (`id`, `name`, `color`, `sort_order`, `active`, `created_at`, `updated_at`, `emoji`) VALUES (1,'Payable By Credit','#8b5cf6',0,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(2,'ACH Payment','#0ea5e9',1,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(3,'Cashapp/Zelle','#22c55e',2,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?'),(4,'Cash Only','#f59e0b',3,1,'2026-06-28 23:48:25','2026-06-29 13:41:01','?');
/*!40000 ALTER TABLE `payment_types` ENABLE KEYS */;

/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`id`, `name`, `color`, `sort_order`, `active`, `created_at`, `updated_at`, `emoji`) VALUES (1,'Business','#6366f1',0,1,'2026-06-29 04:57:59','2026-06-29 13:41:01','?'),(2,'Cash','#84cc16',1,1,'2026-06-29 04:57:59','2026-06-29 13:41:01','?'),(3,'Debt Repayment','#f97316',2,1,'2026-06-29 04:57:59','2026-06-29 13:41:01','?'),(4,'Deposit','#22c55e',3,1,'2026-06-29 04:57:59','2026-06-29 13:41:01','?'),(5,'Discretionary','#a855f7',4,1,'2026-06-29 04:57:59','2026-06-29 13:41:01','?️'),(6,'Essentials','#0ea5e9',7,1,'2026-06-29 04:57:59','2026-08-26 23:49:32','?'),(7,'Essentials/Discretionary','#14b8a6',8,0,'2026-06-29 04:57:59','2026-09-08 19:53:38','?'),(8,'Fees','#ef4444',9,1,'2026-06-29 04:57:59','2026-08-26 23:49:32','?'),(9,'Food/Groceries','#f59e0b',10,1,'2026-06-29 04:57:59','2026-08-26 23:49:32','?'),(10,'Interest','#eab308',12,0,'2026-06-29 04:57:59','2026-09-08 19:53:50','?'),(11,'Interest/Rewards','#10b981',13,1,'2026-06-29 04:57:59','2026-08-26 23:49:32','?'),(12,'Investing','#3b82f6',14,1,'2026-06-29 04:57:59','2026-08-26 23:49:32','?'),(13,'Housing','#8b5cf6',15,1,'2026-06-29 04:57:59','2026-09-15 20:31:08','?'),(14,'Temporary Debt','#fb7185',16,1,'2026-06-29 04:57:59','2026-08-26 23:49:32','⌛'),(15,'Transfer','#64748b',17,1,'2026-06-29 04:57:59','2026-09-09 08:04:57','?'),(16,'Transportation','#06b6d4',19,1,'2026-06-29 04:57:59','2026-09-11 13:40:36','?'),(17,'Utilities','#d946ef',21,1,'2026-06-29 04:57:59','2026-09-11 13:40:36','⚡'),(86,'Gas','#000000',20,1,'2026-07-04 16:21:38','2026-09-11 13:40:36','?'),(87,'Restaurant/Bar','#f2df64',11,1,'2026-07-21 23:55:33','2026-08-26 23:49:32','?'),(90,'Savings','#4dff79',22,1,'2026-09-09 08:04:22','2026-09-11 13:40:36','?'),(91,'Health','#00fdff',18,1,'2026-09-11 13:40:33','2026-09-11 13:41:44','❤️');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;

/*!40000 ALTER TABLE `sync_settings` DISABLE KEYS */;
INSERT INTO `sync_settings` (`id`, `enabled`, `interval_minutes`, `sync_window_days`, `pending_expiry_days`, `record_balances`, `auto_categorize`, `webhook_enabled`, `lock_until`, `next_run_at`, `last_run_id`, `last_webhook_at`, `created_at`, `updated_at`) VALUES (1,0,60,10,7,1,1,1,NULL,NULL,NULL,NULL,'2026-09-20 09:38:41','2026-09-29 16:30:09');
/*!40000 ALTER TABLE `sync_settings` ENABLE KEYS */;

/*!40000 ALTER TABLE `sql_migrations` DISABLE KEYS */;
INSERT INTO `sql_migrations` (`filename`, `applied_at`, `note`) VALUES ('0000_init.sql','2026-09-24 16:57:48','baseline'),('0001_add_lookups_and_balances.sql','2026-09-24 16:57:48','baseline'),('0002_add_categories.sql','2026-09-24 16:57:48','baseline'),('0003_add_transfer_link.sql','2026-09-24 16:57:48','baseline'),('0004_add_emoji.sql','2026-09-24 16:57:48','baseline'),('0004_add_transfer_dismissals.sql','2026-09-24 16:57:49','baseline'),('0005_add_credit_limit.sql','2026-09-24 16:57:49','baseline'),('0006_add_debts.sql','2026-09-24 16:57:49','baseline'),('0007_unify_balances.sql','2026-09-24 16:57:49','baseline'),('0008_drop_debts.sql','2026-09-24 16:57:49','baseline'),('0009_add_txn_bill_link.sql','2026-09-24 16:57:49','baseline'),('0010_add_suggestion_dismissals.sql','2026-09-24 16:57:49','baseline'),('0011_txn_bill_fk_set_null.sql','2026-09-24 16:57:49','baseline'),('0012_add_savings_goals.sql','2026-09-24 16:57:49','baseline'),('0013_add_pay_schedule.sql','2026-09-24 16:57:49','baseline'),('0015_add_txn_notes.sql','2026-09-24 16:57:49','baseline'),('0016_add_cash_allocations.sql','2026-09-24 16:57:49','baseline'),('0017_add_budgets.sql','2026-09-24 16:57:49','baseline'),('0018_budget_auto_rebalance.sql','2026-09-24 16:57:49','baseline'),('0019_savings_line_kind.sql','2026-09-24 16:57:49','baseline'),('0020_add_txn_category_rule.sql','2026-09-24 16:57:49','baseline'),('0020_budget_locks_and_projection_snapshots.sql','2026-09-24 16:57:49','baseline'),('0021_budget_lines_locked_default.sql','2026-09-24 16:57:49','baseline'),('0022_add_txn_pending.sql','2026-09-24 16:57:50',NULL),('0023_add_transaction_splits.sql','2026-09-27 01:47:15',NULL);
/*!40000 ALTER TABLE `sql_migrations` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

