#!/usr/bin/env bash
# Regenerates tests/db/schema.sql — the structure the local test database is built from,
# plus the rows the app treats as configuration (lookup tables, the sync_settings
# singleton). No financial data is ever dumped.
#
# Taken from the database in .env.local rather than from drizzle/, because the
# sql_migrations ledger on the server has drifted from the files in drizzle/ and the
# server is the source of truth for what the app actually runs against.
#
#   ./scripts/dump-test-schema.sh
set -euo pipefail
cd "$(dirname "$0")/.."

URL=$(grep -m1 '^DATABASE_URL=' .env.local | sed -E 's/^DATABASE_URL="?([^"]*)"?$/\1/')
REST=${URL#mysql://}
USERINFO=${REST%@*}; HOSTPART=${REST##*@}
DB_USER=${USERINFO%%:*}; DB_PASS=${USERINFO#*:}
HOSTPORT=${HOSTPART%%/*}; DB_NAME=${HOSTPART#*/}
DB_HOST=${HOSTPORT%%:*}; DB_PORT=${HOSTPORT##*:}

# Config tables only. Everything else ships empty — a test database carrying your bills
# and transactions would defeat the point.
CONFIG_TABLES="bill_statuses payment_types categories sync_settings sql_migrations"

OUT=tests/db/schema.sql
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# One container for both dumps: the amd64 image is emulated and slow to start.
docker run --rm --platform linux/amd64 \
  -e H="$DB_HOST" -e P="$DB_PORT" -e U="$DB_USER" -e PW="$DB_PASS" -e D="$DB_NAME" -e T="$CONFIG_TABLES" \
  mysql:5.7 sh -c '
    set -e
    FLAGS="-h $H -P $P -u $U -p$PW --single-transaction --no-tablespaces --set-gtid-purged=OFF --skip-add-locks --skip-comments"
    mysqldump $FLAGS --no-data "$D"
    echo
    mysqldump $FLAGS --no-create-info --complete-insert "$D" $T
  ' > "$TMP"

{
  echo "-- Generated by scripts/dump-test-schema.sh from the schema of '$DB_NAME'."
  echo "-- Structure for every table, plus rows for: $CONFIG_TABLES"
  echo "-- Regenerate after any migration. Do not hand-edit."
  echo
  cat "$TMP"
} > "$OUT"

echo "Wrote $OUT: $(grep -c '^CREATE TABLE' "$OUT") tables, $(grep -c '^INSERT INTO' "$OUT") insert statements, $(wc -l < "$OUT") lines"
